apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend-service
spec:
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
