apiVersion: v1
kind: Service
metadata:
  name: nestjs-backend-service
spec:
  selector:
    app: nestjs-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000
  type: NodePort
